language: node_js
node_js:
  - "node"

jobs:
  include:
    - stage: build
      node_js: lts/*
      on:
        tags: true
        all_branches: true
      deploy:
        provider: script
        cleanup: false
        script:
          - npm run build
    - stage: release
      node_js: lts/*
      on:
        tags: true
        all_branches: true
      deploy:
        provider: script
        cleanup: false
        script:
          - npx semantic-release
