language: node_js
node_js:
  - "node"

jobs:
  include:
    - stage: release
      node_js: lts/*
      on:
        tags: true
        all_branches: true
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run release
