version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
            - run: npm test
  smokeTest:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run build
            - run: npm run test:smoke
  releaseDryRun:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: "[[ $CI_PULL_REQUEST != '' ]] && npm run release-dry-run || exit 0"
  release:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run release
workflows:
  test-release:
    jobs:
      - test
      - smokeTest:
          requires:
            - test
      - releaseDryRun
      - release:
          requires:
            - smokeTest
          filters:
            branches:
              only:
                - master
