name: Pull Request
on: [pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Unit test
        run: npm test
      - name: Timezone unit test
        run: npm run test:timezone
      - name: Build
        run: npm run build
      - name: Smoke test
        run: npm run test:smoke
